# Generated by Django 3.1.5 on 2021-02-03 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone number')),
            ],
            options={
                'verbose_name': 'Phone Book',
                'verbose_name_plural': 'Phones Book',
                'db_table': 'phones_book',
            },
        ),
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Middle Name/ Patronymic Name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last Name')),
                ('date_of_birth', models.DateField(max_length=8, verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('-', 'Not mentioned')], default='-', max_length=1, verbose_name='Gender')),
                ('address_1', models.CharField(blank=True, max_length=40, null=True, verbose_name='Address 1')),
                ('address_2', models.CharField(max_length=30, verbose_name='Address 2')),
                ('city', models.CharField(max_length=20, verbose_name='City')),
                ('county', models.CharField(max_length=20, verbose_name='County')),
                ('state', models.CharField(choices=[('-', 'Not mentioned'), ('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], default='-', max_length=2, verbose_name='State')),
                ('postal_code', models.CharField(max_length=14, verbose_name='Postal Code')),
                ('country', models.CharField(max_length=20, verbose_name='Country')),
                ('role', models.CharField(max_length=10, verbose_name='Client or Employee')),
                ('phone_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_info', to='generalInfo.phonebook', verbose_name='Phone Book')),
            ],
            options={
                'verbose_name': 'Info Log',
                'verbose_name_plural': 'Info Logs',
                'db_table': 'general_info',
            },
        ),
    ]
