# Generated by Django 3.1.5 on 2021-02-05 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generalInfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalinfo',
            name='phone_book',
        ),
        migrations.AddField(
            model_name='phonebook',
            name='general_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='generalInfo.generalinfo', verbose_name='General Info'),
            preserve_default=False,
        ),
    ]
